import Link from 'next/link'
import GuidedEnquiry from './GuidedEnquiry'
import { HiArrowRight } from 'react-icons/hi'

type CardItem = { title: string; excerpt: string; icon?: string; href?: string }
type StepItem = { number: string; title: string; text: string }
type FaqItem = { question: string; answer: string }
export default function CategoryHub({ eyebrow, title, description, stats, cards, steps, faqs, ctaTitle, ctaDescription, formPage, formTitle, serviceOptions }: { eyebrow: string; title: string; description: string; stats: { label: string; value: string }[]; cards: CardItem[]; steps: StepItem[]; faqs: FaqItem[]; ctaTitle: string; ctaDescription: string; formPage: string; formTitle: string; serviceOptions?: string[] }) {
 return <div className="section-surface category-hub"><section className="category-intro"><div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><div className="category-stats">{stats.map(item => <div key={item.label}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div></section><section className="category-lines"><div className="category-heading"><span className="eyebrow">Choose a focus</span><h2>Support that meets the<br/><em>real requirement.</em></h2></div><div className="category-card-grid">{cards.map(card => <a key={card.title} href="#enquiry" className="category-card"><span>{card.icon || card.title.slice(0, 2).toUpperCase()}</span><h3>{card.title}</h3><p>{card.excerpt}</p><b>Start here <HiArrowRight /></b></a>)}</div></section><section className="category-process"><div className="category-heading"><span className="eyebrow">How it works</span><h2>A clear route from<br/><em>question to action.</em></h2></div><div className="category-step-grid">{steps.map(step => <article key={step.number}><span>{step.number}</span><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section><section className="category-faq"><div><span className="eyebrow">Frequently asked</span><h2>Things worth knowing<br/>before you begin.</h2></div><div>{faqs.map(item => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></section><section className="category-cta"><div><span className="eyebrow">Your next step</span><h2>{ctaTitle}</h2><p>{ctaDescription}</p><Link href="/services" className="text-cta">Explore all services <HiArrowRight /></Link></div><GuidedEnquiry page={formPage} title={formTitle} serviceOptions={serviceOptions} /></section></div>
}
