import Link from 'next/link'
import Nav from '../../components/Nav'
import Footer from '../../components/Footer'
import GuidedEnquiry from '../../components/GuidedEnquiry'
import { prisma } from '../../lib/prisma'
import { sampleServices } from '../../lib/sampleData'
import { HiArrowRight, HiBriefcase, HiChartBar, HiAcademicCap, HiTrendingUp, HiOfficeBuilding, HiKey, HiCheck } from 'react-icons/hi'
const details: Record<string, { icon: any; copy: string; flow: string }> = { consultancy: { icon: HiBriefcase, copy: 'Compliance, registrations and practical business structure.', flow: 'Discover ? map ? execute ? handover' }, finance: { icon: HiChartBar, copy: 'Funding and planning support for personal and business decisions.', flow: 'Assess ? shortlist ? submit ? track' }, education: { icon: HiAcademicCap, copy: 'Learning support, study material and capability building.', flow: 'Understand ? organise ? support ? follow up' }, investment: { icon: HiTrendingUp, copy: 'Growth and protection choices framed around your long-term goals.', flow: 'Review ? strategise ? implement ? review' }, 'real-estate': { icon: HiOfficeBuilding, copy: 'Residential and commercial opportunities considered clearly.', flow: 'Discover ? shortlist ? review ? close' }, 'rental-space': { icon: HiKey, copy: 'Residential and commercial spaces matched to your need.', flow: 'Define ? search ? tour ? finalise' } }
const defaults = Object.keys(details).map(slug => ({ title: slug === 'real-estate' ? 'Real Estate' : slug === 'rental-space' ? 'Rental Space' : slug[0].toUpperCase() + slug.slice(1), slug }))
const shared = ['A single point of contact', 'A practical, transparent process', 'Support that connects the next decision']
export default function Services({ services }: { services: any[] }) { const items = Array.from(new Map([...(services || []), ...sampleServices, ...defaults].map(item => [item.slug, item])).values()).filter((item: any) => details[item.slug]); return <div className="rebuild-services-page"><Nav /><main><section className="services-hero"><div className="container"><p className="eyebrow"><span /> The service ecosystem</p><h1>Expertise for the moves that shape your <em>future.</em></h1><p>Choose the area closest to your current need. We will help connect it to the broader picture.</p></div></section><section className="services-portfolio"><div className="container"><div className="portfolio-grid">{items.map((service: any, index: number) => { const item = details[service.slug]; const Icon = item.icon; return <article key={service.slug} className="portfolio-card"><div><span>0{index + 1}</span><Icon /></div><h2>{service.title}</h2><p>{service.excerpt || item.copy}</p><small>{item.flow}</small><Link href={'/services/' + service.slug}>Explore {service.title} <HiArrowRight /></Link></article> })}</div></div></section><section className="service-principles"><div className="container"><p className="eyebrow">Why it works</p><h2>One view. The right<br/><em>specialist at the right time.</em></h2><div>{shared.map(item => <p key={item}><HiCheck /> {item}</p>)}</div></div></section><section className="service-journey"><div className="container"><p className="eyebrow"><span /> Your journey</p><div className="journey-grid"><h2>From your first question<br/>to a clear next step.</h2><ol><li><span>01</span><div><strong>Share the context</strong><p>Tell us what is happening and what you need to move.</p></div></li><li><span>02</span><div><strong>Meet the right route</strong><p>We connect you with the most relevant service path.</p></div></li><li><span>03</span><div><strong>Move with confidence</strong><p>You receive clear ownership and a practical next action.</p></div></li></ol></div></div></section><section className="rebuild-contact compact"><div className="container rebuild-contact-grid"><div><p className="eyebrow">Not sure where to start?</p><h2>Start with the outcome,<br/><em>not the category.</em></h2><p>We can help you find the right route.</p></div><GuidedEnquiry page="Services" title="Tell us what you are working towards." /></div></section></main><Footer /></div> }
export async function getStaticProps() { try { const services = await prisma.service.findMany(); return { props: { services: JSON.parse(JSON.stringify(services)) }, revalidate: 60 } } catch { return { props: { services: sampleServices }, revalidate: 60 } } }
